# Generated by Django 5.1.2 on 2024-10-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telod", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicinename",
            name="name",
            field=models.CharField(max_length=511),
        ),
    ]
