# Generated by Django 5.1.2 on 2024-10-25 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telod", "0002_alter_medicinename_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="main_name",
            field=models.CharField(default=123, max_length=511, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medicinename",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="telod.medicine"
            ),
        ),
    ]
