# Generated by Django 5.1.2 on 2024-10-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telod", "0003_medicine_main_name_alter_medicinename_medicine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="main_name",
            field=models.CharField(max_length=511),
        ),
    ]
